import streamlit as st
import pandas as pd
from datetime import datetime
from utils.session import get_df, get_raw_df, is_data_loaded
from utils.llm import call_llm, get_active_model
import io


def build_full_context(df: pd.DataFrame) -> str:
    numeric_cols = df.select_dtypes(include="number").columns.tolist()
    cat_cols = df.select_dtypes(include="object").columns.tolist()

    parts = []
    parts.append(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns")
    parts.append(f"Columns: {', '.join(df.columns.tolist())}")

    if numeric_cols:
        desc = df[numeric_cols].describe().round(2)
        parts.append("\nNumeric Statistics:\n" + desc.to_string())

    if cat_cols:
        parts.append("\nCategorical Columns:")
        for col in cat_cols[:4]:
            top = df[col].value_counts().head(3)
            parts.append(f"  {col}: {dict(top)}")

    quality_report = st.session_state.get("quality_report")
    if quality_report:
        parts.append(f"\nData Quality Score: {quality_report['score']}/100")
        parts.append(f"Completeness: {quality_report['completeness']}%")
        parts.append(f"Duplicates: {quality_report['duplicate_rows']} rows")

    insights = st.session_state.get("insights_text")
    if insights:
        parts.append(f"\nAI Insights Summary:\n{insights[:800]}")

    return "\n".join(parts)


def generate_markdown_report(df: pd.DataFrame, llm_report: str, file_name: str) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    numeric_cols = df.select_dtypes(include="number").columns.tolist()
    cat_cols = df.select_dtypes(include="object").columns.tolist()

    quality_report = st.session_state.get("quality_report")
    insights_text = st.session_state.get("insights_text", "Not generated.")

    lines = []
    lines.append(f"# 📊 Data Analysis Report")
    lines.append(f"**File:** {file_name}  ")
    lines.append(f"**Generated:** {now}  ")
    lines.append(f"**Tool:** CSV Insight Agents\n")
    lines.append("---\n")

    lines.append("## 1. Dataset Overview\n")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Rows | {df.shape[0]:,} |")
    lines.append(f"| Columns | {df.shape[1]} |")
    lines.append(f"| Numeric Columns | {len(numeric_cols)} |")
    lines.append(f"| Categorical Columns | {len(cat_cols)} |")
    lines.append(f"| Missing Cells | {df.isnull().sum().sum():,} |")
    lines.append(f"| Duplicate Rows | {df.duplicated().sum()} |\n")

    if quality_report:
        lines.append("## 2. Data Quality\n")
        lines.append(f"**Overall Score: {quality_report['score']}/100**\n")
        lines.append("| Dimension | Score |")
        lines.append("|-----------|-------|")
        lines.append(f"| Completeness | {quality_report['completeness']}% |")
        lines.append(f"| Validity | {quality_report['validity']}% |")
        lines.append(f"| Consistency | {quality_report['consistency']}% |")
        lines.append(f"| Duplicate Rate | {quality_report['duplicate_rate']}% |\n")

    if numeric_cols:
        lines.append("## 3. Statistical Summary\n")
        # Convert dataframe to string without using tabulate
        desc_df = df[numeric_cols].describe().round(3)
        lines.append(desc_df.to_string())
        lines.append("")

    lines.append("## 4. AI-Generated Insights\n")
    lines.append(insights_text)
    lines.append("")

    lines.append("## 5. Full Analysis Report\n")
    lines.append(llm_report)
    lines.append("")

    lines.append("---")
    lines.append(f"*Report generated by CSV Insight Agents · {now}*")

    return "\n".join(lines)


def render():
    st.markdown("## 📄 Report Writing Agent")
    st.markdown("Compiles all agent outputs into a comprehensive, downloadable analysis report.")
    st.markdown("---")

    if not is_data_loaded():
        st.warning("No data loaded. Please upload a CSV on the Home page first.")
        return

    df = get_df()
    file_name = st.session_state.get("file_name", "data.csv")

    # Pipeline status
    st.markdown("#### 📋 Pipeline Completion Status")

    steps = [
        ("🔍 Data Quality", st.session_state.get("quality_report") is not None),
        ("🧹 Data Cleaning", st.session_state.get("cleaning_report") is not None),
        ("📊 Statistical Analysis", st.session_state.get("stats_done", False)),
        ("📈 Visualization", st.session_state.get("viz_done", False)),
        ("💡 AI Insights", st.session_state.get("insights_text") is not None),
    ]

    # Create status indicators
    cols = st.columns(len(steps))
    for col, (label, done) in zip(cols, steps):
        color = "#34d399" if done else "#64748b"
        icon = "✅" if done else "⏳"
        col.markdown(f"""
        <div style="text-align:center;padding:0.5rem;background:rgba(255,255,255,0.05);
                    border-radius:12px;border:1px solid {color}44;">
            <div style="font-size:1.2rem;">{icon}</div>
            <div style="font-size:0.7rem;color:{color};margin-top:0.3rem;">{label}</div>
        </div>
        """, unsafe_allow_html=True)

    completed = sum(1 for _, done in steps if done)
    st.markdown(f"<br><p style='color:rgba(255,255,255,0.6);font-size:0.85rem;'>{completed}/{len(steps)} steps completed. You can generate the report at any stage.</p>", unsafe_allow_html=True)

    st.markdown("---")

    # Report options
    st.markdown("#### ⚙️ Report Options")
    report_tone = st.selectbox(
        "Report tone",
        ["Executive (non-technical)", "Technical (data science)", "Mixed"],
        help="Choose the writing style for your report"
    )
    include_recs = st.checkbox("Include recommendations section", value=True)

    if st.button("▶ Generate Full Report", use_container_width=False, type="primary"):
        context = build_full_context(df)

        system_prompt = f"""You are a senior data analyst writing a professional analysis report.
Tone: {report_tone}.
Write clearly, use structure (headings, bullet points), and be specific with numbers.
This report will be read by {'business stakeholders' if 'Executive' in report_tone else 'technical teams'}.
"""

        user_prompt = f"""Write a comprehensive data analysis report based on the following dataset analysis.

{context}

Structure your report with these sections:
1. **Executive Summary** (3-4 sentences)
2. **Key Findings** (5 bullet points with specific data)
3. **Data Quality Assessment** (brief)
4. **Trend Analysis** (patterns observed)
{'5. **Strategic Recommendations** (3 concrete, actionable items)' if include_recs else ''}

Keep the report professional, specific, and under 600 words."""

        with st.spinner("📝 Writing report..."):
            llm_report = call_llm(user_prompt, system_prompt, max_tokens=1400)
            st.session_state.report_text = llm_report

            # Build full markdown report
            full_report = generate_markdown_report(df, llm_report, file_name)
            st.session_state.full_report_md = full_report

        st.success("✅ Report generated successfully!")

    # Display report
    if st.session_state.get("report_text"):
        st.markdown("---")
        st.markdown("#### 📄 Generated Report")

        # Display report in a nice container
        st.markdown(f"""
        <div style="background:linear-gradient(135deg, rgba(255,255,255,0.08), rgba(255,255,255,0.03));
                    backdrop-filter: blur(10px);
                    border: 1px solid rgba(102,126,234,0.3);
                    border-radius: 16px;
                    padding: 1.8rem;
                    line-height: 1.8;
                    font-family: monospace;
                    font-size: 0.9rem;
                    white-space: pre-wrap;">
            {st.session_state.report_text.replace(chr(10), '<br>')}
        </div>
        """, unsafe_allow_html=True)

        st.markdown("<br>", unsafe_allow_html=True)

        # Download options
        st.markdown("#### ⬇️ Download Report")
        col1, col2, col3 = st.columns(3)

        with col1:
            st.download_button(
                "📄 Download as Markdown (.md)",
                data=st.session_state.get("full_report_md", ""),
                file_name=f"analysis_report_{file_name.replace('.csv','')}.md",
                mime="text/markdown",
                use_container_width=True,
            )

        with col2:
            st.download_button(
                "📝 Download as Text (.txt)",
                data=st.session_state.get("report_text", ""),
                file_name=f"analysis_report_{file_name.replace('.csv','')}.txt",
                mime="text/plain",
                use_container_width=True,
            )

        with col3:
            # Create CSV download option for the cleaned data
            csv_buffer = io.StringIO()
            df.to_csv(csv_buffer, index=False)
            st.download_button(
                "📊 Download Cleaned CSV",
                data=csv_buffer.getvalue(),
                file_name="cleaned_data.csv",
                mime="text/csv",
                use_container_width=True,
            )

        # Completion message
        st.markdown("---")
        st.markdown("""
        <div style="background:linear-gradient(135deg, rgba(0,176,155,0.2), rgba(150,201,61,0.2));
                    border:1px solid rgba(0,176,155,0.5);
                    border-radius:16px;
                    padding:1.2rem;
                    text-align: center;">
            <p style="color:#34d399;font-weight:700;font-size:1.1rem;margin:0;">
                🎉 Analysis Complete!
            </p>
            <p style="color:rgba(255,255,255,0.7);margin:0.5rem 0 0 0;font-size:0.85rem;">
                You've completed the analysis pipeline. Upload a new CSV on the Home page to start fresh.
            </p>
        </div>
        """, unsafe_allow_html=True)
        
        # Button to start over
        if st.button("🏠 Return to Home", use_container_width=True):
            st.session_state.current_page = "home"
            st.rerun()
            
    else:
        st.info("Click **Generate Full Report** to compile the final analysis from all agents.")
